spring:
  application:
    name: security

  security:
    user:
      name: user
      password: user

  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update   # or validate / create-drop / none
    show-sql: true       # optional, remove in prod

